// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMmYgPjxr6LvFCTATEuL5oKqtlF_kxgxI',
    appId: '1:572588099361:web:10ae0fba8185e43139a060',
    messagingSenderId: '572588099361',
    projectId: 'smartpesa-6bb50',
    authDomain: 'smartpesa-6bb50.firebaseapp.com',
    storageBucket: 'smartpesa-6bb50.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-pwf8EjHYDZpt5_XiNZfihXs9DHswHQs',
    appId: '1:572588099361:android:6ef19e6d0308c75139a060',
    messagingSenderId: '572588099361',
    projectId: 'smartpesa-6bb50',
    storageBucket: 'smartpesa-6bb50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm1VZf7cCiFr24m-OaYYSvGP3HAy-Ixug',
    appId: '1:572588099361:ios:934dc82b8ec5777439a060',
    messagingSenderId: '572588099361',
    projectId: 'smartpesa-6bb50',
    storageBucket: 'smartpesa-6bb50.firebasestorage.app',
    iosBundleId: 'com.example.uiFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm1VZf7cCiFr24m-OaYYSvGP3HAy-Ixug',
    appId: '1:572588099361:ios:934dc82b8ec5777439a060',
    messagingSenderId: '572588099361',
    projectId: 'smartpesa-6bb50',
    storageBucket: 'smartpesa-6bb50.firebasestorage.app',
    iosBundleId: 'com.example.uiFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMmYgPjxr6LvFCTATEuL5oKqtlF_kxgxI',
    appId: '1:572588099361:web:6f9fea4c133b0cc739a060',
    messagingSenderId: '572588099361',
    projectId: 'smartpesa-6bb50',
    authDomain: 'smartpesa-6bb50.firebaseapp.com',
    storageBucket: 'smartpesa-6bb50.firebasestorage.app',
  );
}
